name: Github Checks
on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:
permissions: write-all
jobs:
  gitleaks:
    uses: djay21/centralized-workflows/.github/workflows/gitleaks.yml@main
    ##secrets: inherit
  regula:
    uses: djay21/centralized-workflows/.github/workflows/rego.yml@main
    ##secrets: inherit
  terraform:
    uses: djay21/centralized-workflows/.github/workflows/terraform-gcp.yml@main
    ##secrets: inherit
