---
name: "Regula Scan"
on:
  pull_request:
    paths:
      - '**/*.tf'
  workflow_call:
  
jobs:
  regula:
    name: "Regula scan"
    runs-on: ubuntu
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    defaults:
      run:
        working-directory: ${{ github.workspace }}/
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.3.5
      - name: configure Regula
        run: |
          wget -q https://github.com/fugue/regula/releases/download/v2.6.1/regula_2.6.1_Linux_x86_64.tar.gz 
          tar -xf regula_2.6.1_Linux_x86_64.tar.gz
          mv regula /tmp 
      - name: Compliance check
        run: |
          /tmp/regula run  . -f table | tee ${{ github.workspace }}/compliance-report.json
          echo -e "\n\n****** Overall Results *******\n\n" >> ${{ github.workspace }}/compliance-report.json
          /tmp/regula run . -f json | jq .summary.rule_results >> ${{ github.workspace }}/compliance-report.json
      - name: Comment Regula Status on PR
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.number }}
          body-path: compliance-report.json